name: iStore Upload

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'work/**'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    name: iStore Upload
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@main
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 1

      - name: New Pending
        run: git push -f origin HEAD:pending
