name: iStore Upload

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'work/**'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    name: iStore Upload
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 1

      - name: New Pending
        run: git push -f origin HEAD:pending