name: iStore Pending

on:
  pull_request:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  others:
    if: github.event_name == 'pull_request' && !(github.head_ref == 'pending' && github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name)
    runs-on: ubuntu-latest
    name: iStore Fail on main
    steps:
      - name: Fail
        run: |
          echo "Must merge from pending branch" >&2
          exit 1

  pending:
    if: github.event_name != 'pull_request' || (github.head_ref == 'pending' && github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name)
    runs-on: ubuntu-latest
    name: iStore Pending Check
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

