name: iStore PR Pending check

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
    branches:
      - pending

env:
  TZ: Asia/Shanghai

jobs:
  check_pending:
    if: github.event.action != 'edited' || github.event.changes.base.ref.from != github.event.pull_request.base.ref
    runs-on: ubuntu-latest
    name: Workflows HACK check
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout base on PR to pending
        uses: actions/checkout@main
        with:
          fetch-depth: 1
          path: 'base'

      - name: Checkout head on PR to pending
        uses: actions/checkout@main
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1
          path: 'head'

      - name: Check workflows changes on PR to pending
        run: |
          [ -d base/.github/workflows ]
          [ -d head/.github/workflows ]
          rm -rf base/.github/workflows
          cp -a head/.github/workflows base/.github/
          if git -C base diff --pretty= --name-only --no-renames | grep -q '^.github/workflows/'; then \
            echo "Don't HACK my workflows!" >&2; \
            echo "::error title=PR Check failed::Don't touch workflows!"; \
            exit 1; \
          else \
            true; \
          fi

      - name: Check pass
        run: |
          echo "PASS"
          true

