name: iStore PR check

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
    branches-ignore:
      - pending

env:
  TZ: Asia/Shanghai

jobs:
  check:
    if: (github.event.action != 'edited' || github.event.changes.base.ref.from != github.event.pull_request.base.ref) && !((github.head_ref == 'pending' || github.head_ref == 'ci/automerging') && github.event.pull_request.base.repo.full_name == github.event.pull_request.head.repo.full_name)
    runs-on: ubuntu-latest
    name: PR target branch check
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: iStore Fail on pr to main
        run: |
          echo "Must PR to pending branch!" >&2
          echo "::error title=PR Check failed::You MUST PR to pending branch!"
          exit 1

