name: TestAPP

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  testapp:
    runs-on: ubuntu-latest
    name: TestAPP
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: main
          fetch-depth: 1

      - name: Push pending
        run: |
          git push -f origin HEAD:pending

