name: TestAPI

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  testapi:
    runs-on: ubuntu-latest
    name: TestAPI
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: create pr
        id: create_pr
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const oldprs = await github.rest.pulls.list({
              owner:context.repo.owner,
              repo:context.repo.repo,
              state:"open",
              head:"ci/automerging",
              base:"main",
              per_page:1
            })
            if (oldprs.status >= 200 && oldprs.status < 300 && oldprs.data.length > 0) {
              const pr_num=oldprs.data[0].number
              console.log("PR already existed, update #", pr_num)
              await github.rest.pulls.update({
                owner:context.repo.owner,
                repo:context.repo.repo,
                pull_number:pr_num,
                body: "# Test Content\nLine2\n```bash\necho hi\n```\n"
              })
              return pr_num
            } else {
              const pr = await github.rest.pulls.create({
                owner:context.repo.owner,
                repo:context.repo.repo,
                title:"Auto Merging",
                head:"ci/automerging",
                base:"main",
                body:"# Test Content\nLine2\n```bash\necho hi\n```\n"
              })
              if (pr.status >= 200 && pr.status < 300) {
                console.log("PR created #", pr.data.number)
                return pr.data.number
              }
            }

      - name: merge pr
        uses: actions/github-script@v7
        env:
          PULL_NUMBER: ${{steps.create_pr.outputs.result}}
        with:
          script: |
            const { PULL_NUMBER } = process.env
            const mr = await github.rest.pulls.merge({
              owner:context.repo.owner,
              repo:context.repo.repo,
              pull_number:PULL_NUMBER,
              merge_method:"rebase"
            })
            console.log(mr)


